name: chedoan
description: Ứng dụng theo dõi dinh dưỡng hàng ngày.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core functionality
  provider: ^6.0.5
  flutter_bloc: ^9.1.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  crypto: ^3.0.3

  # Firebase
  firebase_core: ^2.24.2  
  firebase_auth: ^4.15.3
  firebase_database: ^10.5.7
  
  flutter_lints: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true